export const ADD_STEP = 'ADD_STEP'
export const DELETE_STEP = 'DELETE_STEP'
export const REORDER_STEPS = 'REORDER_STEPS'
export const SELECT_FOR_EDITING = 'SELECT_FOR_EDITING'
export const SELECT_FOR_PREVIEW = 'SELECT_FOR_PREVIEW'

export const UPDATE_STEP = 'UPDATE_STEP'
export const UPDATE_STEP_HEADING = 'UPDATE_STEP_HEADING'
export const UPDATE_STEP_TYPE = 'UPDATE_STEP_TYPE'
export const UPDATE_PATHWAY_NAME = 'UPDATE_PATHWAY_NAME'
export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
export const UPDATE_PATHWAY_INITIAL_STATE = 'UPDATE_PATHWAY_INITIAL_STATE'

export const TOGGLE_PATHWAY_DETAILS_SCREEN = 'TOGGLE_PATHWAY_DETAILS_SCREEN'
export const TOGGLE_MODAL_CLOSE_ON_OVERLAY = 'TOGGLE_MODAL_CLOSE_ON_OVERLAY'

export const ADD_NEW_PATHWAY = 'ADD_NEW_PATHWAY'
export const POP_LAST_PATHWAY = 'POP_LAST_PATHWAY'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'