export const ADD_STEP = 'ADD_STEP'
export const DELETE_STEP = 'DELETE_STEP'
export const REORDER_STEPS = 'REORDER_STEPS'
export const SELECT_FOR_EDITING = 'SELECT_FOR_EDITING'
export const SELECT_FOR_PREVIEW = 'SELECT_FOR_PREVIEW'

export const UPDATE_STEP = 'UPDATE_STEP'
export const UPDATE_STEP_HEADING = 'UPDATE_STEP_HEADING'
export const UPDATE_STEP_TYPE = 'UPDATE_STEP_TYPE'
export const UPDATE_PATHWAY_NAME = 'UPDATE_PATHWAY_NAME'
export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'

export const ADD_NEW_PATHWAY = 'ADD_NEW_PATHWAY'
export const POP_LAST_PATHWAY = 'POP_LAST_PATHWAY'

export const USER_LOGIN = 'USER_LOGIN'
